from __future__ import annotations

from datetime import datetime, timezone
import os
from pathlib import Path
import shutil
from typing import Any

import yaml

from hydrolite.project import PROJECT_REQUIRED_DIRS, validate_project, write_project_summary


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_ROOT = PROJECT_ROOT / "templates" / "wizard"


def _read_yaml(path: str | Path) -> dict[str, Any]:
    data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"Wizard YAML root must be a mapping: {path}")
    return data


def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8")


def _resolve_from_root(value: str | Path | None) -> Path | None:
    if value in (None, ""):
        return None
    path = Path(str(value)).expanduser()
    return path if path.is_absolute() else (PROJECT_ROOT / path).resolve()


def _relative_to_project(project_dir: Path, path: Path | None) -> str:
    if path is None:
        return ""
    try:
        return path.resolve().relative_to(project_dir.resolve()).as_posix()
    except ValueError:
        return Path(os.path.relpath(path.resolve(), project_dir.resolve())).as_posix()


def load_wizard_template(template_name: str = "basic") -> dict[str, Any]:
    name = template_name
    if not name.endswith((".yaml", ".yml")):
        name = f"{name}_project.yaml" if name == "basic" else f"{name}.yaml"
    path = TEMPLATE_ROOT / name
    if not path.exists():
        raise FileNotFoundError(f"Wizard template not found: {path}")
    return _read_yaml(path)


def validate_wizard_config(wizard_config: str | Path | dict[str, Any]) -> dict[str, Any]:
    config = _read_yaml(wizard_config) if isinstance(wizard_config, (str, Path)) else dict(wizard_config)
    errors: list[str] = []
    warnings: list[str] = []
    project = config.get("project") or {}
    data = config.get("data") or {}
    case = config.get("case") or {}
    if not project.get("name"):
        errors.append("project.name is required.")
    if not project.get("id"):
        errors.append("project.id is required.")
    if not case.get("name"):
        errors.append("case.name is required.")
    for key in ("rainfall_csv", "subbasin_csv", "reach_csv"):
        path = _resolve_from_root(data.get(key))
        if path is None:
            errors.append(f"data.{key} is required.")
        elif not path.exists():
            errors.append(f"data.{key} not found: {path}")
    for key in ("observed_streamflow_csv", "swmm_inp", "basin_boundary"):
        value = data.get(key)
        if value:
            path = _resolve_from_root(value)
            if path is not None and not path.exists():
                warnings.append(f"Optional data.{key} not found: {path}")
    modules = config.get("modules") or {}
    if modules.get("swmm") and not data.get("swmm_inp"):
        warnings.append("SWMM module enabled but data.swmm_inp is empty.")
    return {
        "status": "failed" if errors else "passed",
        "errors": errors,
        "warnings": warnings,
        "project_name": project.get("name", ""),
        "project_id": project.get("id", ""),
        "case_name": case.get("name", ""),
    }


def generate_project_yaml_from_wizard(wizard_config: dict[str, Any]) -> dict[str, Any]:
    project = wizard_config.get("project") or {}
    modules = wizard_config.get("modules") or {}
    return {
        "project_name": project.get("name", "Wizard Project"),
        "project_id": project.get("id", "wizard_project"),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "description": project.get("description", "Project generated by HydroLite Studio project wizard."),
        "author": project.get("author", "HydroLite Studio"),
        "version": "0.6.0-dev",
        "paths": {
            "cases_dir": "cases",
            "configs_dir": "configs",
            "data_dir": "data",
            "output_dir": "output",
            "reports_dir": "reports",
            "logs_dir": "logs",
        },
        "modules": {
            "hydrolite": bool(modules.get("hydrolite", True)),
            "swmm": bool(modules.get("swmm", False)),
            "gee": bool(modules.get("gee", False)),
            "openhydronet": bool(modules.get("openhydronet", False)),
        },
        "default_cases": [f"{(wizard_config.get('case') or {}).get('name', 'wizard_case')}.yaml"],
        "notes": ["Generated by HydroLite Studio project wizard.", "Input files are referenced by relative path."],
    }


def copy_or_reference_input_files(wizard_config: dict[str, Any], project_dir: str | Path | None = None) -> dict[str, str]:
    project_path = Path(project_dir or wizard_config.get("_project_dir") or ".").expanduser().resolve()
    data = wizard_config.get("data") or {}
    mode = str(data.get("mode", "reference"))
    result: dict[str, str] = {"mode": mode}
    for key in ("rainfall_csv", "subbasin_csv", "reach_csv", "observed_streamflow_csv", "swmm_inp", "basin_boundary"):
        source = _resolve_from_root(data.get(key))
        if source is None:
            result[key] = ""
            continue
        if mode == "copy":
            target = project_path / "data" / source.name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            result[key] = _relative_to_project(project_path, target)
        else:
            result[key] = _relative_to_project(project_path, source)
    return result


def generate_case_from_wizard(wizard_config: dict[str, Any]) -> dict[str, Any]:
    project_dir = Path(wizard_config.get("_project_dir") or ".").expanduser().resolve()
    case = wizard_config.get("case") or {}
    modules = wizard_config.get("modules") or {}
    inputs = copy_or_reference_input_files(wizard_config, project_dir)
    rainfall = Path(inputs["rainfall_csv"])
    subbasin = Path(inputs["subbasin_csv"])
    reach = Path(inputs["reach_csv"])
    case_yaml: dict[str, Any] = {
        "name": case.get("name", "wizard_case"),
        "model": {"time_step_hours": float(case.get("time_step_hours", 1.0))},
        "inputs": {
            "directory": ".",
            "rainfall": rainfall.as_posix(),
            "subcatchments": subbasin.as_posix(),
            "reaches": reach.as_posix(),
        },
        "outputs": {"directory": f"output/{case.get('name', 'wizard_case')}"},
    }
    if inputs.get("observed_streamflow_csv"):
        case_yaml["observed"] = {
            "enabled": True,
            "observed_streamflow_csv": inputs["observed_streamflow_csv"],
            "time_column": "datetime",
            "flow_column": "observed_streamflow_m3s",
            "gauge_id_column": "gauge_id",
        }
    if modules.get("swmm") and inputs.get("swmm_inp"):
        case_yaml["swmm"] = {
            "enabled": True,
            "inp_file": inputs["swmm_inp"],
            "coupling": {
                "enabled": True,
                "source_flow_csv": f"output/{case.get('name', 'wizard_case')}/result_flow.csv",
                "source_time_column": "time",
                "source_flow_column": "outflow_cms",
                "target_node": "J1",
                "inflow_name": "HYDROLITE_INFLOW",
                "flow_unit": "CMS",
            },
        }
    return case_yaml


def _copy_optional_configs(project_dir: Path) -> None:
    configs = project_dir / "configs"
    configs.mkdir(parents=True, exist_ok=True)
    for name in ("gee.example.yaml", "openhydronet.example.yaml"):
        source = PROJECT_ROOT / "configs" / name
        if source.exists():
            shutil.copy2(source, configs / name)


def write_wizard_summary(project_dir: str | Path) -> Path:
    project_path = Path(project_dir).expanduser().resolve()
    summary = write_project_summary(project_path)
    extra = project_path / "reports" / "wizard_summary.md"
    extra.parent.mkdir(parents=True, exist_ok=True)
    cases = sorted(path.name for path in (project_path / "cases").glob("*.y*ml"))
    extra.write_text(
        "\n".join(
            [
                "# Wizard Summary",
                "",
                f"Project directory: `{project_path}`",
                f"Generated cases: {', '.join(cases) if cases else 'none'}",
                f"Project summary: `{summary}`",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return extra


def preview_wizard(wizard_config: str | Path | dict[str, Any]) -> dict[str, Any]:
    config = _read_yaml(wizard_config) if isinstance(wizard_config, (str, Path)) else dict(wizard_config)
    validation = validate_wizard_config(config)
    data_refs = copy_or_reference_input_files(config, PROJECT_ROOT / "projects" / str((config.get("project") or {}).get("id", "wizard_project")))
    return {
        "project_name": validation["project_name"],
        "project_id": validation["project_id"],
        "modules": config.get("modules") or {},
        "cases": [f"{validation['case_name']}.yaml"],
        "data": data_refs,
        "missing_files": validation["errors"] + validation["warnings"],
        "status": validation["status"],
    }


def create_project_from_wizard(wizard_config: str | Path | dict[str, Any], project_dir: str | Path | None = None, force: bool = False) -> dict[str, Any]:
    config = _read_yaml(wizard_config) if isinstance(wizard_config, (str, Path)) else dict(wizard_config)
    validation = validate_wizard_config(config)
    if validation["errors"]:
        raise ValueError("; ".join(validation["errors"]))
    target = Path(project_dir or (PROJECT_ROOT / "projects" / str((config.get("project") or {}).get("id", "wizard_project")))).expanduser().resolve()
    if target.exists() and any(target.iterdir()) and not force:
        raise FileExistsError(f"Project already exists and is not empty: {target}")
    config["_project_dir"] = str(target)
    for directory in PROJECT_REQUIRED_DIRS:
        (target / directory).mkdir(parents=True, exist_ok=True)
    _write_yaml(target / "project.yaml", generate_project_yaml_from_wizard(config))
    case_yaml = generate_case_from_wizard(config)
    _write_yaml(target / "cases" / f"{case_yaml['name']}.yaml", case_yaml)
    _copy_optional_configs(target)
    (target / "data" / "README.md").write_text(
        "# Wizard Project Data\n\nInput files are referenced or copied according to the wizard template.\n",
        encoding="utf-8",
    )
    write_wizard_summary(target)
    validation_outputs = validate_project(target)
    return {
        "project_dir": target,
        "project_yaml": target / "project.yaml",
        "case_file": target / "cases" / f"{case_yaml['name']}.yaml",
        "wizard_summary": target / "reports" / "wizard_summary.md",
        "validation_xlsx": validation_outputs["xlsx"],
    }
